import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Toaster } from "sonner";
import Providers from "@/lib/providers/Providers";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const Bahnschrift = localFont({
  src: "../../public/fonts/Bahnschrift.woff2",
  variable: "--font-Bahnschrift",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Bahnschrift.className}>
        <AppRouterCacheProvider>
          <Toaster position="top-right" />
          <Providers>{children}</Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
